config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  get '/signup', to:'users#new'
  root 'static_pages#top'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/all_index', to: 'users#all_index'

  get '/processing', to: 'receptions#processing'
  get '/electricity', to: 'receptions#electricity'
  get '/assembly', to: 'receptions#assembly'

  resources :receptions 

      resources :users do

        get 'information'

        member do

          #残業申請関連
          get 'attendances/reception_request'            #日報申請ページ
          patch 'attendances/reception_update'           #日報申請patch

          get 'attendances/reception_edit'               #日報編集ページ
          patch 'attendances/reception_edit'             #日報編集申請patch

          get 'attendances/reception_index'              #日報一覧
          get 'attendances/reception_day'                #日報詳細モーダル(個人)

          get 'attendances/receipts_list'                #日報一覧
          delete 'attendances/receipts_destroy'          #各日報削除
          get 'attendances/receipts_day_list'            #日報日毎データ
          get 'attendances/receipts_day'                 #日報詳細モーダル(管理者)


        end

          resources :attendances, only: :update do
            member do
              patch 'receipts/receipts_update'           #日報反映patch
              get 'admin_reception_request'              #admin日報編集ページ
              patch 'admin_reception_update'             #admin日報更新
              get 'admin_reception_index'                #admin用受付一覧
              get 'reset_receptions'                     #受付リセット
            end
          end
      end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX  },
                    uniqueness: true

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  validates :name_code, presence: true
  validates :position, presence: true
  validates :department, presence: true
  validates :specialty, presence: true

  mount_uploader :image, ImageUploader
  


  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end


  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

def authenticated?(remember_token)
  return false if remember_digest.nil?
  BCrypt::Password.new(remember_digest).is_password?(remember_token)
end

  def forget
    update_attribute(:remember_digest, nil)
  end

end 

app/controllers/users_controller.rb
class UsersController < ApplicationController

 before_action :set_user, only: [:show, :edit, :update, :destroy]
 before_action :logged_in_user, only: [:show, :edit, :update, :index, :destroy, :information, :new]
 before_action :correct_user, only: [:edit, :update]
 before_action :admin_user, only: [:destroy, :create, :new]
 before_action :not_admin_user, only: [:index]


  def new
    @user = User.new
  end


  def index
    @users = User.paginate(page: params[:page])
    @user_g = User.find_by(position: "グループリーダー")
    @users_t = User.where(position: "チームリーダー")
    
    @class_text =
    case current_user.specialty
    when "加工" 
      'common-processing'
    when "電気"
      'common-electricity'
    when "組立"
      'common-assembly'
    end

    @specialty_name =
    case current_user.specialty
    when "加工" 
      '加工チーム'
    when "電気"
      '電気チーム'
    when "組立"
      '組立チーム'
    end
  end



  def all_index
    @users = User.all
    @user_g = User.find_by(position: "グループリーダー")
    @users_t = User.where(position: "チームリーダー")
  
  end


  def show
  end


  def create
    @user = User.new(user_params)
     if @user.save
      if @user.position == "チームリーダー"
        @user.update(team_superior: true)
      end
      flash[:success] = '新規作成に成功しました。'
      redirect_to all_index_url
     else
      render :new
     end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "個人情報を更新しました。"
      redirect_to attendances_reception_index_user_url(@user)
    else
      render :edit      
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to all_index_url
  end


  def information
    @user = User.find_by(id: params[:user_id])
  end

  private

  def user_params
    params.require(:user).permit(:name,
                                 :email, 
                                 :team_superior,
                                 :group_superior,
                                 :name_code,
                                 :position,
                                 :image,
                                 :department,
                                 :specialty,
                                 :password, 
                                 :password_confirmation)
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "ログインしてください"
      redirect_to login_url
    end
  end

  def correct_user
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to root_url unless current_user.admin?
  end

  def not_admin_user
    if current_user.admin?
      redirect_to(root_url)
      flash[:danger] ="権限がありません"
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>

<%= f.label :name, class: "label-#{yield(:class_text)}" %>
<%= f.text_field :name, class: "form-control"  %>

<%= f.label :email, class: "label-#{yield(:class_text)}" %>
<%= f.email_field :email, class: "form-control" %>

<div class="row">
  <div class="col-md-5">

    <%= f.label :name_code, class: "label-#{yield(:class_text)}" %>
    <%= f.number_field :name_code, min: 1, class: "form-control" %>

    <%= f.label :position, class: "label-#{yield(:class_text)}" %>
    <%= f.select :position,['','メンバー','チームリーダー'],{}, class: "form-control" %>

    <%= f.label :department, class: "label-#{yield(:class_text)}" %>
    <%= f.select :department,['','試作部'],{}, class: "form-control" %>

    <%= f.label :specialty, class: "label-#{yield(:class_text)}" %>
    <%= f.select :specialty,['','組立','加工','電気'],{}, class: "form-control" %>
  </div>
</div>



<%= f.label :password, class: "label-#{yield(:class_text)}" %>
<%= f.password_field :password, class: "form-control" %>

<%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
<%= f.password_field :password, class: "form-control" %>

<%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>

<% end %>

app/views/users/_information.html.erb
<% provide(:title, "edit") %>
<% provide(:class_text, "edit") %>
<% provide(:button_text, "更新") %>

<div class="modal-dialog modal-dialog-center">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>

<div class="row">
  <div class="col-md-12">

<%= form_with(model: @user, local: true) do |f| %>

  <% if @user.image.present? %>

      <%= image_tag @user.image.url %>

  <% end %>
     
  <br>
  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, readonly: true, class: "form-control"  %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, readonly: true, class: "form-control" %>

  <div class="row">
    <div class="col-md-5">

      <%= f.label :name_code, class: "label-#{yield(:class_text)}" %>
      <%= f.number_field :name_code, readonly: true, min: 1, class: "form-control" %>
      
      <%= f.label :position, class: "label-#{yield(:class_text)}" %>
      <%= f.select :position,['','メンバー','チームリーダー','グループリーダー'],{}, disabled: true, class: "form-control" %>

      <%= f.label :department, class: "label-#{yield(:class_text)}" %>
      <%= f.select :department, ['','試作部'],{}, disabled: true, class: "form-control" %>

      <%= f.label :specialty, class: "label-#{yield(:class_text)}" %>
      <%= f.select :specialty, ['','組立','加工','電気'],{}, disabled: true, class: "form-control" %>

     
    </div>
  </div>

<% end %>

  </div>
</div>

    </div>
  </div>
</div>

app/views/users/all_index.html.erb
<% provide(:title, "全メンバー一覧") %>

<h2>全メンバー一覧</h2>


<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="position">【グループリーダー】</div>
    <table class="table table-bordered table-striped table-condensed table-hover" id="table-users">
      <thead>
        <tr>
          <th>氏名コード</th>
          <th>名前</th>
          <th>所属</th>
          <th>専門</th>
          <th>チームリーダー</th>
          <th>個人情報</th>

          <% if current_user.admin? %>
          <th>日報編集</th>
          <th>削除</th>
          <% end %>

        </tr>

      </thead>

      <tbody>
        <% @users.each do |user| %>
        <% if user.group_superior? %>
        <tr>
          <td><%= user.name_code %></td>
          <td><%= user.name %></td>
          <td><%= user.department %></td>
          <td><%= user.specialty %></td>
          <td>-</td>
          <td>
            <%= link_to "個人情報", user_information_path(user), class: "btn btn-info btn-sm", remote: true %>
          </td>

          <% if current_user.admin? %>
          <td></td>
          <td><%= link_to "削除", user_path(user), method: :delete,
                                  data: { confirm: "削除してよろしいですか？" },
                                  class: "btn btn-danger btn-sm" %></td>
          <% end %>

        </tr>
        <% end %>
        <% end %>
      </tbody>


    </table>
  </div>
</div>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="position">【チームリーダー】</div>
    <table class="table table-bordered table-striped table-condensed table-hover" id="table-users">
      <thead>


      </thead>

      <tbody>
        <% @users.each do |user| %>
        <% if user.team_superior? %>
        <tr>
          <td><%= user.name_code %></td>
          <td><%= user.name %></td>
          <td><%= user.department %></td>
          <td><%= user.specialty %></td>
          <td><%= user.name %></td>
          <td>
            <%= link_to "個人情報", user_information_path(user), class: "btn btn-info btn-sm", remote: true %>
          </td>

          <% if current_user.admin? %>
          <td><%= link_to "日報編集", attendances_reception_index_user_path(user), class: "btn btn-primary btn-sm" %></td>
          <td><%= link_to "削除", user_path(user), method: :delete,
                                     data: { confirm: "削除してよろしいですか？" },
                                     class: "btn btn-danger btn-sm" %></td>
          <% end %>

        </tr>
        <% end %>
        <% end %>
      </tbody>

    </table>
  </div>
</div>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="position">【メンバー】</div>
    <table class="table table-bordered table-striped table-condensed table-hover" id="table-users">
      <thead>

      </thead>

      <tbody>
        <% @users.each do |user| %>
        <% if user.specialty == "加工" %>
        <% if user.group_superior == false &&
            user.team_superior == false &&
            user.admin == false %>
        <tr>
          <td><%= user.name_code %></td>
          <td><%= user.name %></td>
          <td><%= user.department %></td>
          <td><%= user.specialty %></td>
          <td>
            <% if user.specialty == "加工" %>
            <% @users_t.each do |t| %>
            <% if t.specialty == "加工" %>
            <%= t.name %><br>
            <% end %>
            <% end %>
            <% end %>
          </td>
          <td>
            <%= link_to "個人情報", user_information_path(user), class: "btn btn-info btn-sm", remote: true %>
          </td>

          <% if current_user.admin? %>
          <td><%= link_to "日報編集", attendances_reception_index_user_path(user), class: "btn btn-primary btn-sm" %></td>
          <td><%= link_to "削除", user_path(user), method: :delete, 
                                    data: { confirm: "削除してよろしいですか？" },
                                    class: "btn btn-danger btn-sm" %></td>
          <% end %>

        </tr>
        <% end %>
        <% end %>
        <% end %>

        <% @users.each do |user| %>
        <% if user.specialty == "電気" %>
        <% if user.group_superior == false &&
            user.team_superior == false &&
            user.admin == false %>
        <tr>
          <td><%= user.name_code %></td>
          <td><%= user.name %></td>
          <td><%= user.department %></td>
          <td><%= user.specialty %></td>
          <td>
            <% if user.specialty == "電気" %>
            <% @users_t.each do |t| %>
            <% if t.specialty == "電気" %>
            <%= t.name %><br>
            <% end %>
            <% end %>
            <% end %>
          </td>
          <td>
            <%= link_to "個人情報", user_information_path(user), class: "btn btn-info btn-sm", remote: true %>
          </td>

          <% if current_user.admin? %>
          <td><%= link_to "日報編集", attendances_reception_index_user_path(user), class: "btn btn-primary btn-sm" %></td>
          <td><%= link_to "削除", user_path(user), method: :delete, class: "btn btn-danger btn-sm" %></td>
          <% end %>

        </tr>
        <% end %>
        <% end %>
        <% end %>

        <% @users.each do |user| %>
        <% if user.specialty == "組立" %>
        <% if user.group_superior == false &&
            user.team_superior == false &&
            user.admin == false %>
        <tr>
          <td><%= user.name_code %></td>
          <td><%= user.name %></td>
          <td><%= user.department %></td>
          <td><%= user.specialty %></td>
          <td>
            <% if user.specialty == "組立" %>
            <% @users_t.each do |t| %>
            <% if t.specialty == "組立" %>
            <%= t.name %><br>
            <% end %>
            <% end %>
            <% end %>
          </td>
          <td>
            <%= link_to "個人情報", user_information_path(user), class: "btn btn-info btn-sm", remote: true %>
          </td>

          <% if current_user.admin? %>
          <td><%= link_to "日報編集", attendances_reception_index_user_path(user), class: "btn btn-primary btn-sm" %></td>
          <td><%= link_to "削除", '#', class: "btn btn-danger btn-sm" %></td>
          <% end %>

        </tr>
        <% end %>
        <% end %>
        <% end %>
      </tbody>

    </table>
  </div>
</div>

<div id="information" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/error_messages', object: @user %>
  </div>
</div>

<div class="common-container">
  <div class="common-content">
    <div class="container">
      <h1>個人情報修正</h1>

      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "チームメンバー一覧") %>

<h2>チームメンバー一覧</h2>


<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="position">【グループリーダー】</div>
    <table class="table table-bordered table-condensed table-hover" id="table-users">
      <thead>
        <tr>
          <th>氏名コード</th>
          <th>名前</th>
          <th>所属</th>
          <th>専門</th>
          <th>チームリーダー</th>
          <th>確認</th>

        </tr>

      </thead>

      <tbody>
        <% @users.each do |user| %>
        <% if user.group_superior? %>
        <tr>
          <td><%= user.name_code %></td>
          <td><%= user.name %></td>
          <td><%= user.department %></td>
          <td><%= user.specialty %></td>
          <td>-</td>
          <td><%= link_to "個人情報", user_information_path(user), class: "btn btn-info btn-sm ", remote: true %></td>
        </tr>
        <% end %>
        <% end %>
      </tbody>


    </table>
  </div>
</div>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="position">【チームリーダー】</div>
    <table class="table table-bordered table-condensed table-hover" id="table-users">


      <% @users.each do |user| %>
      <% if user.team_superior? && (current_user.specialty == user.specialty) %>
      <tr>
        <td><%= user.name_code %></td>
        <td><%= user.name %></td>
        <td><%= user.department %></td>
        <td><%= user.specialty %></td>
        <td><%= @user_g.name %></td>
        <td><%= link_to "個人情報", user_information_path(user), class: "btn btn-info btn-sm ", remote: true %></td>
      </tr>
      <% end %>
      <% end %>
      </tbody>

    </table>
  </div>
</div>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="position">【メンバー】</div>
    <table class="table table-bordered table-condensed table-hover" id="table-users">

      <tbody>
        <% @users.each do |user| %>
        <% if user.group_superior == false &&
            user.team_superior == false &&
            user.admin == false && (current_user.specialty == user.specialty) %>
        <tr>
          <td><%= user.name_code %></td>
          <td><%= user.name %></td>
          <td><%= user.department %></td>
          <td><%= user.specialty %></td>

          <% @users_t.each do |user_t| %>
          <% if current_user.specialty == user_t.specialty %>
          <td><%= user_t.name %></td>
          <% end %>
          <% end %>

          <td><%= link_to "個人情報", user_information_path(user), class: "btn btn-info btn-sm", remote: true %></td>
        </tr>
        <% end %>
        <% end %>


    </table>
  </div>
</div>


<div id="information" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/users/information.js.erb
$("#information").html("<%= escape_javascript(render 'information') %>");
$("#information").modal("show");

app/views/users/new.html.erb
<% provide(:title, "Signup") %>
<% provide(:class_text, "signup") %>
<% provide(:button_text, "新規作成") %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/error_messages', object: @user %>
  </div>
</div>


<h2>新規登録</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name ) %>
<h1><%= @user.name %>, <%= @user.email %></h1>