config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  get '/signup', to:'users#new'
  root 'static_pages#top'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/all_index', to: 'users#all_index'

  get '/processing', to: 'receptions#processing'
  get '/electricity', to: 'receptions#electricity'
  get '/assembly', to: 'receptions#assembly'

  resources :receptions 

      resources :users do

        get 'information'

        member do

          #残業申請関連
          get 'attendances/reception_request'            #日報申請ページ
          patch 'attendances/reception_update'           #日報申請patch

          get 'attendances/reception_edit'               #日報編集ページ
          patch 'attendances/reception_edit'             #日報編集申請patch

          get 'attendances/reception_index'              #日報一覧
          get 'attendances/reception_day'                #日報詳細モーダル(個人)

          get 'attendances/receipts_list'                #日報一覧
          delete 'attendances/receipts_destroy'          #各日報削除
          get 'attendances/receipts_day_list'            #日報日毎データ
          get 'attendances/receipts_day'                 #日報詳細モーダル(管理者)


        end

          resources :attendances, only: :update do
            member do
              patch 'receipts/receipts_update'           #日報反映patch
              get 'admin_reception_request'              #admin日報編集ページ
              patch 'admin_reception_update'             #admin日報更新
              get 'admin_reception_index'                #admin用受付一覧
              get 'reset_receptions'                     #受付リセット
            end
          end
      end

end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  has_many :receipts, dependent: :destroy
  has_many :daily_receipts, dependent: :destroy
  
  validates :worked_on, presence: true
  
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController

  before_action :set_user, only: [:reception_request, :reception_update, :reception_index, :reception_day]
  before_action :set_one_month, only: [:reception_request, :reception_update, :reception_index, :reception_day  ]
  before_action :set_attendance, only: [:reception_request, :reception_update]
  before_action :set_member_attendance, only: [:admin_reception_update]
  before_action :set_performance, only: [:admin_reception_index]
  before_action :admin_user, only: [:admin_reception_request, :admin_reception_update,
                                    :admin_reception_index, :receipts_list, :receipts_day_list]
  before_action :admin_or_correct_user, only: [:reception_index, :reception_request, :reception_update]
  before_action :not_admin_user, only: [:reception_index]
  before_action :reception_validates, only: [:reception_update, :admin_reception_update]
  before_action :business_trip_validates, only: [:reception_update, :admin_reception_update]
  

  #日報提出ページ
  def reception_request
    @receipts = Receipt.where(attendance_id: @attendance.id)
    @receptions = Reception.all
  end

  #日報提出更新
  def reception_update
    #DailyReceiptから当日のattendanceIDで抽出
    @daily_receipts = DailyReceipt.where(attendance_id: @attendance.id)
    #当日日報がある場合は、削除
    if @daily_receipts.present?
      @daily_receipts.each do |d|
        d.destroy
      end
    end
  
    #受付詳細が送られて来ている場合
    if d_receipt_params.present?
      d_receipt_params.each do |id, item|
        attendance = Attendance.find_by(id: @attendance.id)
        @daily_receipt = attendance.daily_receipts.build(item)
        @daily_receipt.save
        receipt = Receipt.find(id)
        @daily_receipt.update(d_receipt_time: receipt.receipt_time)
      end
    end
      redirect_to attendances_reception_index_user_url(current_user)
        flash[:success] = "日報を提出しました"
  end

  #日報編集ページ
  def reception_edit
  end

  #日報編集更新ページ
  def reception_edit
  end

  #個人日報一覧ページ
  def reception_index
  end

  #日報詳細
  def reception_day
    @attendance = @attendances.find_by(worked_on: params[:date])
    @daily_receipts = DailyReceipt.where(attendance_id: @attendance.id)
  end

  
  #日報一覧カレンダー
  def receipts_list
    @attendances = Attendance.all
  end

  #日報日毎データ一覧
  def receipts_day_list
    @attendances = Attendance.where(worked_on: params[:date] )
    attendance = Attendance.find(params[:id])
    @users = User.all
  end

  def receipts_destroy
    @attendances = Attendance.where(worked_on: params[:date])
    @user = User.find_by(id: params[:id])
    @attendance = @attendances.find_by(user_id: @user.id)
    @daily_receipts = DailyReceipt.where(attendance_id: @attendance.id)

    @attendance.destroy
    @daily_receipts.each do |d|
      d.destroy
    end
    redirect_to attendances_receipts_day_list_user_url(current_user, date: params[:date])
    flash[:success] = "#{@user.name}の日報を削除しました"
  end

  #日報詳細(個人)
  def receipts_day
    @attendances = Attendance.where(worked_on: params[:date])
    @user = User.find_by(id: params[:id])
    @attendance = @attendances.find_by(user_id: @user.id)
    @daily_receipts = DailyReceipt.where(attendance_id: @attendance.id)
  end


  #admin 日報編集ページ
  def admin_reception_request
    #送られた日付データとidから該当のattendanceを抽出
    @attendance = Attendance.find_by(id: params[:id])

    #attendanceからuserを抽出
    @user = User.find_by(id: @attendance.user_id)
    #抽出したattendanceから紐づいたdaily_receiptを抽出
    @daily_receipt = DailyReceipt.find_by(attendance_id: @attendance.id)
    #抽出したattendanceから紐づいたreceiptを抽出
    @receipts = Receipt.where(attendance_id: @attendance.id)
  end

   #日報提出更新
   def admin_reception_update
    #DailyReceiptから当日のattendanceIDで抽出
    @daily_receipts = DailyReceipt.where(attendance_id: @attendance.id)
    #当日日報がある場合は、削除
    if @daily_receipts.present?
      @daily_receipts.each do |d|
        d.destroy
      end
    end

    #受付詳細が送られて来ている場合
    if d_receipt_params.present?
      d_receipt_params.each do |id, item|
        attendance = Attendance.find_by(id: @attendance.id)
        @daily_receipt = attendance.daily_receipts.build(item)
        @daily_receipt.save
        receipt = Receipt.find(id)
        @daily_receipt.update(d_receipt_time: receipt.receipt_time)
      end
    end
    redirect_to attendances_receipts_day_list_user_url(current_user, date: @attendance.worked_on )
    flash[:success] = "日報を更新しました"
end

  def admin_reception_index
    #送られた日付データとidから該当のattendanceを抽出
    @attendance = Attendance.find_by(id: params[:id])
    #attendanceからuserを抽出
    @user = User.find_by(id: @attendance.user_id)
    @receptions = Reception.all
    @processings = Reception.where(reception_specialty: "加工")
    @electricitys = Reception.where(reception_specialty: "電気")
    @assemblys = Reception.where(reception_specialty: "組立")

    @receptions.each do |reception|
      reception.update(check: "0")
    end
  end


  def reset_receptions
    @attendance = Attendance.find(params[:id])
    @user = User.find_by(id: @attendance.user_id)
    @receptions = Reception.all

    @receptions.each do |reception|
      reception.update(check: 0, check_id: nil)
    end

    @receipts = Receipt.where(attendance_id: @attendance.id)
    if @receipts.present?
      @receipts.each do |receipt|
        receipt.destroy
      end
    end

    if current_user.admin?
      redirect_to admin_reception_request_user_attendance_path(@user, @attendance)
      flash[:success] = "受付情報をリセットしました"
    else
      redirect_to attendances_reception_request_user_url(current_user)
      flash[:success] = "受付情報をリセットしました"
    end


  end




  private

  def attendances_params
    params.require(:user).permit(attendances: [:clean_time,
                                               :meeting_time,
                                               :other_time,
                                               :over_time,
                                               :classification,
                                               :working_time,
                                               :designation_time,
                                               :address])[:attendances]
  end

  def d_receipt_params
    params.require(:user).permit(daily_receipts: [:d_receipt_namuber,
                                                  :d_receipt_name,
                                                  :d_receipt_specialty])[:daily_receipts]
  end

  def receipts_params
    params.require(:user).permit(receipts: [:receipt_time])[:receipts]
  end




end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/attendances/admin_reception_index.html.erb
<% provide(:title, "all_reception") %>

<h1>受付日報一覧(管理者)</h1>

<%= form_with(model: @user, url: receipts_receipts_update_user_attendance_path(@user, @attendance), 
              local: true, method: :patch) do |f| %>
<div class="row">
  <div class="col-md-10 col-md-offset-1">

    <%= link_to "新規作成", new_reception_path, class: "btn btn-primary", remote: true %>
    <%= f.submit "反映", class: "btn btn-primary" %>
    <div style="margin-bottom: 20px;"></div>

    <% if @processings.present? %>
    <div class="processings">【加工業務受付】</div>
    <% elsif @electricitys.present? %>
    <div class="processings">【電気業務受付】</div>
    <% elsif @assemblys.present? %>
    <div class="processings">【組立業務受付】</div>
    <% end %>

    <table class="table table-bordered table-striped table-condensed table-hover" id="table-receptions">
      <thead>
        <tr>
          <th>受付No</th>
          <th>受付名</th>
          <th>規定工数 [h]</th>
          <th>使用可能工数 [h]</th>
          <th>実績工数 [min]</th>
          <th>反映</th>
          <th>編集</th>
        </tr>

      </thead>


      <tbody>
        <% if @processings.present? %>
        <% @processings.each do |processing| %>
        <%= f.fields_for "receipts[]", processing  do |r| %>
        <%= f.fields_for "receptions[]", processing do |p| %>

        <tr>

          <td><%= processing.reception_namuber %></td>
          <%= r.hidden_field :receipt_namuber, value: processing.reception_namuber %>

          <td><%= processing.reception_name %></td>
          <%= r.hidden_field :receipt_name, value: processing.reception_name %>

          <td><%= processing.reception_time %></td>
          <td><%= processing.reception_remainder_time %></td>
          <td><%= processing.reception_Performance_time %></td>
          <td><%= p.check_box :check %></td>
          <%= p.hidden_field :check_id, value: processing.id %>
          <td>
            <%= link_to "編集", edit_reception_path(processing), class: "btn btn-primary btn-sm", remote: true %>
            <%= link_to "削除", reception_path(processing), method: :delete,
                                  data: { confirm: "削除してよろしいですか？" },
                                  class: "btn btn-danger btn-sm" %>
          </td>

          <%= r.hidden_field :receipt_specialty, value: "加工" %>
        </tr>
        <% end %>
        <% end %>
        <% end %>
        <% end %>
    </table>

    <% if @electricitys.present? %>
    <div class="processings">【電気業務受付】</div>
    <table class="table table-bordered table-striped table-condensed table-hover" id="table-receptions">
      <% @electricitys.each do |electricity| %>
      <%= f.fields_for "receipts[]", electricity do |r| %>
      <%= f.fields_for "receptions[]", electricity do |e| %>
      <tr>
        <td><%= electricity.reception_namuber %></td>
        <%= r.hidden_field :receipt_namuber, value: electricity.reception_namuber %>

        <td><%= electricity.reception_name %></td>
        <%= r.hidden_field :receipt_name, value: electricity.reception_name %>

        <td><%= electricity.reception_time %></td>
        <td><%= electricity.reception_remainder_time %></td>
        <td><%= electricity.reception_Performance_time %></td>
        <td><%= e.check_box :check %></td>
        <%= e.hidden_field :check_id, value: electricity.id %>
        <td>
          <%= link_to "編集", edit_reception_path(electricity), class: "btn btn-primary btn-sm", remote: true %>
          <%= link_to "削除", reception_path(electricity), method: :delete,
                                  data: { confirm: "削除してよろしいですか？" },
                                  class: "btn btn-danger btn-sm" %>
        </td>
        <%= r.hidden_field :receipt_specialty, value: "電気" %>
      </tr>
      <% end %>
      <% end %>
      <% end %>
      <% end %>
    </table>

    <% if @assemblys.present? %>
    <div class="processings">【組立業務受付】</div>
    <table class="table table-bordered table-striped table-condensed table-hover" id="table-receptions">
      <% @assemblys.each do |assembly| %>
      <%= f.fields_for "receipts[]", assembly do |r| %>
      <%= f.fields_for "receptions[]", assembly do |a| %>
      <tr>
        <td><%= assembly.reception_namuber %></td>
        <%= r.hidden_field :receipt_namuber, value: assembly.reception_namuber %>

        <td><%= assembly.reception_name %></td>
        <%= r.hidden_field :receipt_name, value: assembly.reception_name %>

        <td><%= assembly.reception_time %></td>
        <td><%= assembly.reception_remainder_time %></td>
        <td><%= assembly.reception_Performance_time %></td>
        <td><%= a.check_box :check %></td>
        <%= a.hidden_field :check_id, value: assembly.id %>
        <td>
          <%= link_to "編集", edit_reception_path(assembly), class: "btn btn-primary btn-sm", remote: true %>
          <%= link_to "削除", reception_path(assembly), method: :delete,
                                  data: { confirm: "削除してよろしいですか？" },
                                  class: "btn btn-danger btn-sm" %>
        </td>
        <%= r.hidden_field :receipt_specialty, value: "組立" %>
      </tr>
      <% end %>
      <% end %>
      <% end %>
      <% end %>
    </table>

    </tbody>
  </div>
</div>


<% end %>
<!--モーダルウインドウ表示-->
<div id="new" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/attendances/admin_reception_request.html.erb
<% provide(:title, "日報編集") %>
<% provide(:class_text, "edit") %>

<h2>日報編集(管理者)</h2>
<h2><%= @user.name %></h2>
<h2><%= l(@attendance.worked_on) %></h2>

<%= form_with(model: @user, url: admin_reception_update_user_attendance_path(@user, data: @attendance), method: :patch ) do |f| %>
<%= f.fields_for :attendances, @attendance do |a| %>


<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="pull-right"><%= link_to "リセット", reset_receptions_user_attendance_path(@user, @attendance), class: "btn btn-sm", id: "add200" %></div>
    <div class="pull-right"><%= link_to "受付取得", admin_reception_index_user_attendance_path(@user, date: @attendance), class: "btn btn-info btn-sm" %></div>
    <div style="margin-bottom: 40px;"></div>
    <table class="table table-bordered table-condensed table-hover" id="table-users">
      <thead>
      <tbody>
        <tr>
          <th>受付No</th>
          <% if @receipts.present? %>
          <% @receipts.each do |receipt| %>
          <%= f.fields_for "daily_receipts[]", receipt do |r| %>
          <td><%= receipt.receipt_namuber %></td>
          <%= r.hidden_field :d_receipt_namuber, value: receipt.receipt_namuber %>
          <% end %>
          <% end %>
          <% else %>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <% end %>

        </tr>
        <tr>
          <th>業務名</th>

          <% if @receipts.present? %>
          <% @receipts.each do |receipt| %>
          <%= f.fields_for "daily_receipts[]", receipt do |r| %>
          <td><%= receipt.receipt_name %></td>
          <%= r.hidden_field :d_receipt_name, value: receipt.receipt_name %>
          <% end %>
          <% end %>
          <% else %>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <% end %>
        </tr>

        <tr>
          <th>業務種類</th>

          <% if @receipts.present? %>
          <% @receipts.each do |receipt| %>
          <%= f.fields_for "daily_receipts[]", receipt do |r| %>
          <td><%= receipt.receipt_specialty %></td>
          <%= r.hidden_field :d_receipt_specialty, value: receipt.receipt_specialty %>
          <% end %>
          <% end %>
          <% else %>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <% end %>
        <tr>

        <tr>
          <th>業務時間</th>

          <% if @receipts.present? %>
          <%= f.hidden_field :'#', id: "count", value: @receipts.count %>
          <% @receipts.each_with_index do |receipt, i| %>
          <%= f.fields_for "receipts[]", receipt do |r| %>
          <td><%= r.number_field :receipt_time, id: "add10#{i}", class: "form-control", min: 0, placeholder: '分' %></td>
          <% end %>
          <% end %>
          <% else %>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <% end %>
        </tr>

        </thead>
      </tbody>
    </table>

    <div class="row">
      <div class="col-md-6">
        <h3>その他</h3>


        <table class="table table-bordered table-condensed table-hover" id="table-users">
          <thead>
          <tbody>
            <tr>
              <th>4S</th>
              <td><%= a.number_field :clean_time, id: "add2", class: "form-control", min: 0, placeholder: '分' %></td>
            </tr>

            <tr>
              <th>朝礼/昼礼</th>
              <td><%= a.number_field :meeting_time, id: "add3", class: "form-control", min: 0, placeholder: '分' %></td>
            </tr>

            <tr>
              <th>その他</th>
              <td><%= a.number_field :other_time, id: "add4", class: "form-control", min: 0, placeholder: '分'%></td>
            </tr>

            <tr>
              <th>残業時間</th>
              <td><%= a.select :over_time, ['','0','0.25', '0.5', '0.75', '1.0',
                                        '1.25', '1.5', '1.75', '2.0',
                                        '2.25', '2.5', '2.75', '3.0' ], {}, id: "add6", class: "form-control" %></td>
            </tr>

            <tr>
              <th>出勤区分</th>
              <td><%= a.select :classification, ['通常','出張', '特別勤務'], {}, class: "form-control" %></td>
            </tr>

            <tr>
              <th>勤務時間</th>
              <td><%= a.text_field :working_time, id: "add5",readonly: true, class: "form-control" %></td>

            </tr>


            <tr>
              <th>勤務指定時間</th>
              <td><%= a.text_field :designation_time, id: "add10",readonly: true, class: "form-control" %></td>
            </tr>

          </tbody>
          </thead>


        </table>
      </div>

      <div class="col-md-6" id="column1">
        <h3>Google-Map</h3>



        <div id='map'></div>

        <style>
          #map {
            height: 400px;
            width: 100%;
          }
        </style>

        <script>
          let map

          function initMap() {
            geocoder = new google.maps.Geocoder()

            map = new google.maps.Map(document.getElementById('map'), {
              center: {
                lat: 40.7828,
                lng: -73.9653
              },
              zoom: 12,
            });

            marker = new google.maps.Marker({
              position: {
                lat: 40.7828,
                lng: -73.9653
              },
              map: map
            });
          }
          // ここから追加 
          let geocoder

          function codeAddress() {
            let inputAddress = document.getElementById('address').value;

            geocoder.geocode({
              'address': inputAddress
            }, function(results, status) {
              if (status == 'OK') {
                map.setCenter(results[0].geometry.location);
                var marker = new google.maps.Marker({
                  map: map,
                  position: results[0].geometry.location
                });
              } else {
                alert('該当する結果がありませんでした：' + status);
              }
            });
          }
          // ここまで追加 
        </script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDl0E5bZ1VTtLlaJlHP1msZZuAAjb_8zj4&callback=initMap" async defer></script>
        <!-- ここから追加 -->

        <%= a.text_field :address, id: "address",placeholder: '出張先住所を入力してください', class: "form-control" %>
        <div class="google-map-search">
          <input type="button" value="Encode" onclick="codeAddress()">
        </div>
        <!-- ここまで追加-->
      </div>
    </div>





    <%= f.submit "提出", class: "btn btn-primary btn-block" %>


  </div>
</div>
<% end %>

<% end %>

app/views/attendances/receipts_day.js.erb
$("#receipts_day").html("<%= escape_javascript(render 'receipts_day') %>");
$("#receipts_day").modal("show");

app/views/attendances/receipts_day_list.html.erb
<% provide(:title, "日報提出者一覧") %>


<h2>
  <% @attendances.each do |day| %>
  <%= day.worked_on %>
  <% break %>
  <% end %>
</h2>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="position">【メンバー一覧】</div>
    <table class="table table-bordered table-condensed table-hover" id="table-users">

      <thead>
        <tr>
          <th>氏名コード</th>
          <th>名前</th>
          <th>所属</th>
          <th>専門</th>
          <th>確認</th>
          <th>削除</th>


        </tr>

      </thead>

      <tbody>
        <% @users.each do |user| %>
        <% @attendances.each do |a| %>
        <% if user.id == a.user_id && a.working_time.present? %>
        <tr>
          <td><%= user.name_code %></td>
          <td><%= user.name %></td>
          <td><%= user.department %></td>
          <td><%= user.specialty %></td>

          <td><%= link_to "日報確認", attendances_receipts_day_user_path(user, date: a.worked_on), class: "btn btn-info btn-sm", remote: true %></td>
          <td><%= link_to "削除", attendances_receipts_destroy_user_path(user, date: a.worked_on),method: :delete,
                                                                         data: { confirm: "削除してよろしいですか？" },
                                                                         class: "btn btn-danger btn-sm" %></td>
        </tr>
        <% end %>
        <% end %>
        <% end %>


    </table>
    <div style="margin-top: 500px;"></div>

  </div>
</div>

<div id="receipts_day" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/attendances/reception_request.html.erb
<% provide(:title, "日報提出") %>
<% provide(:class_text, "signup") %>

<h2>日報提出</h2>
<h2><%= l(@attendance.worked_on) %></h2>

<%= form_with(model: @user, url: attendances_reception_update_user_path(@user, data: @attendance), method: :patch ) do |f| %>
<%= f.fields_for :attendances, @attendance do |a| %>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="pull-right"><%= link_to "リセット", reset_receptions_user_attendance_path(@user, @attendance), class: "btn btn-sm", id: "add200" %></div>
    <div class="pull-right"><%= link_to "受付取得", receptions_path, class: "btn btn-info btn-sm" %></div>
    <div style="margin-bottom: 40px;"></div>

    <table class="table table-bordered table-condensed table-hover" id="table-users">
      <thead>
      <tbody>
        <tr>
          <th>受付No</th>

          <% if @receipts.present? %>
          <% @receipts.each do |receipt| %>
          <%= f.fields_for "daily_receipts[]", receipt do |r| %>
          <td><%= receipt.receipt_namuber %></td>
          <%= r.hidden_field :d_receipt_namuber, value: receipt.receipt_namuber %>
          <% end %>
          <% end %>
          <% else %>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <% end %>

        </tr>
        <tr>
          <th>業務名</th>

          <% if @receipts.present? %>
          <% @receipts.each do |receipt| %>
          <%= f.fields_for "daily_receipts[]", receipt do |r| %>
          <td><%= receipt.receipt_name %></td>
          <%= r.hidden_field :d_receipt_name, value: receipt.receipt_name %>
          <% end %>
          <% end %>
          <% else %>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <% end %>
        </tr>

        <tr>
          <th>業務種類</th>

          <% if @receipts.present? %>
          <% @receipts.each do |receipt| %>
          <%= f.fields_for "daily_receipts[]", receipt do |r| %>
          <td><%= receipt.receipt_specialty %></td>
          <%= r.hidden_field :d_receipt_specialty, value: receipt.receipt_specialty %>
          <% end %>
          <% end %>
          <% else %>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <% end %>
        <tr>

        <tr>
          <th>業務時間</th>

          <% if @receipts.present? %>
          <%= f.hidden_field :'#', id: "count", value: @receipts.count %>
          <% @receipts.each_with_index do |receipt, i| %>
          <%= f.fields_for "receipts[]", receipt do |r| %>
          <td><%= r.number_field :receipt_time, id: "add10#{i}", class: "form-control", min: 0, placeholder: '分' %></td>
          <% end %>
          <% end %>
          <% else %>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <% end %>
        </tr>

        </thead>
      </tbody>
    </table>

    <div class="row">
      <div class="col-md-6">
        <h3>その他</h3>


        <table class="table table-bordered table-condensed table-hover" id="table-users">
          <thead>
          <tbody>
            <tr>
              <th>4S</th>
              <td><%= a.number_field :clean_time, id: "add2", class: "form-control", min: 0, placeholder: '分' %></td>
            </tr>

            <tr>
              <th>朝礼/昼礼</th>
              <td><%= a.number_field :meeting_time, id: "add3", class: "form-control", min: 0, placeholder: '分' %></td>
            </tr>

            <tr>
              <th>その他</th>
              <td><%= a.number_field :other_time, id: "add4", class: "form-control", min: 0, placeholder: '分'%></td>
            </tr>

            <tr>
              <th>残業時間</th>
              <td><%= a.select :over_time, ['','0','0.25', '0.5', '0.75', '1.0',
                                        '1.25', '1.5', '1.75', '2.0',
                                        '2.25', '2.5', '2.75', '3.0' ], {}, id: "add6", class: "form-control" %></td>
            </tr>

            <tr>
              <th>出勤区分</th>
              <td><%= a.select :classification, ['通常', '出張', '特別勤務'], {}, id: "add7", class: "form-control" %></td>
            </tr>

            <tr>
              <th>勤務時間</th>
              <td><%= a.text_field :working_time, id: "add5",readonly: true, class: "form-control" %></td>

            </tr>


            <tr>
              <th>勤務指定時間</th>
              <td><%= a.text_field :designation_time, id: "add10",readonly: true, class: "form-control" %></td>
            </tr>

          </tbody>
          </thead>


        </table>


      </div>



      <div class="col-md-6" id="column1">
        <h3>Google-Map</h3>



        <div id='map'></div>

        <style>
          #map {
            height: 400px;
            width: 100%;
          }
        </style>

        <script>
          let map

          function initMap() {
            geocoder = new google.maps.Geocoder()

            map = new google.maps.Map(document.getElementById('map'), {
              center: {
                lat: 40.7828,
                lng: -73.9653
              },
              zoom: 12,
            });

            marker = new google.maps.Marker({
              position: {
                lat: 40.7828,
                lng: -73.9653
              },
              map: map
            });
          }
          // ここから追加 
          let geocoder

          function codeAddress() {
            let inputAddress = document.getElementById('address').value;

            geocoder.geocode({
              'address': inputAddress
            }, function(results, status) {
              if (status == 'OK') {
                map.setCenter(results[0].geometry.location);
                var marker = new google.maps.Marker({
                  map: map,
                  position: results[0].geometry.location
                });
              } else {
                alert('該当する結果がありませんでした：' + status);
              }
            });
          }
          // ここまで追加 
        </script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDl0E5bZ1VTtLlaJlHP1msZZuAAjb_8zj4&callback=initMap" async defer></script>


        <%= a.text_field :address, placeholder: '出張先住所を入力してください', id: "address", class: "form-control" %>

        <div class="google-map-search">
          <input type="button" value="Encode" onclick="codeAddress()">
        </div>

      </div>
    </div>




    <%= f.submit "提出", class: "btn btn-primary btn-block" %>


  </div>
</div>
<% end %>

<% end %>