config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  get '/signup', to:'users#new'
  root 'static_pages#top'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/all_index', to: 'users#all_index'

  get '/processing', to: 'receptions#processing'
  get '/electricity', to: 'receptions#electricity'
  get '/assembly', to: 'receptions#assembly'

  resources :receptions 

      resources :users do

        get 'information'

        member do

          #残業申請関連
          get 'attendances/reception_request'            #日報申請ページ
          patch 'attendances/reception_update'           #日報申請patch

          get 'attendances/reception_edit'               #日報編集ページ
          patch 'attendances/reception_edit'             #日報編集申請patch

          get 'attendances/reception_index'              #日報一覧
          get 'attendances/reception_day'                #日報詳細モーダル(個人)

          get 'attendances/receipts_list'                #日報一覧
          delete 'attendances/receipts_destroy'          #各日報削除
          get 'attendances/receipts_day_list'            #日報日毎データ
          get 'attendances/receipts_day'                 #日報詳細モーダル(管理者)


        end

          resources :attendances, only: :update do
            member do
              patch 'receipts/receipts_update'           #日報反映patch
              get 'admin_reception_request'              #admin日報編集ページ
              patch 'admin_reception_update'             #admin日報更新
              get 'admin_reception_index'                #admin用受付一覧
              get 'reset_receptions'                     #受付リセット
            end
          end
      end

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Daily_management_app", root_path, id: "logo" %>

    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Top", root_path %></li>

        <% if logged_in? %>
        <% if current_user.admin? %>
        <li><%= link_to "メンバー追加",signup_path %></li>
        <li><%= link_to "提出日報一覧",attendances_receipts_list_user_path(current_user) %></li>
        <% end %>
        <% unless current_user.admin? %>
        <li><%= link_to "日報一覧",attendances_reception_index_user_path(current_user) %></li>
        <li><%= link_to "日報提出",attendances_reception_request_user_path(current_user, data: @attendance) %></li>
        <% end %>

        <li><%= link_to "受付一覧", receptions_path %></li>



        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            メンバー一覧 <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <% unless current_user.admin? %>
            <li><%= link_to "チームメンバー一覧", users_path %></li>
            <% end %>
            <li><%= link_to "全メンバー一覧", all_index_path %></li>
          </ul>
        </li>



        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= current_user.name %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <% unless current_user.admin? %>
            <li><%= link_to "個人情報修正", edit_user_path(current_user) %></li>
            <% end %>
            <li class="divider"></li>
            <li>
              <%= link_to "Log out", logout_path, method: :delete %>
            </li>
          </ul>
        </li>

        <% else %>
        <li><%= link_to "Log in", login_path %></li>
        <% end %>


      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>



  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'calculation', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'designation', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'google-map', 'data-turbolinks-track': 'reload' %>

  <%= render 'layouts/shim' %>

</head>


<body>
  <%= render 'layouts/header' %>

  <div class="common-container">
    <div class="common-content">
      <div class="container">
        <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>"><%= msg %></div>
        <% end %>


        <%= yield %>
        <div style="margin-bottom: 500px;"></div>

      </div>
    </div>
  </div>
  </div>

</body>

</html>